package org.multipaz.mdoc.zkp.longfellow

/**
 * Enum for the `MdocProverErrorCode` returned by the native Longfellow prover.
 *
 * The ordinal values must be kept in sync with the `MdocProverErrorCode` enum in the native
 * `mdoc_zk.h` header.
 */
internal enum class ProverCodeEnum(val value: Int) {
    MDOC_PROVER_SUCCESS(0),
    MDOC_PROVER_NULL_INPUT(1),
    MDOC_PROVER_INVALID_INPUT(2),
    MDOC_PROVER_CIRCUIT_PARSING_FAILURE(3),
    MDOC_PROVER_HASH_PARSING_FAILURE(4),
    MDOC_PROVER_WITNESS_CREATION_FAILURE(5),
    MDOC_PROVER_GENERAL_FAILURE(6),
    MDOC_PROVER_MEMORY_ALLOCATION_FAILURE(7),
    MDOC_PROVER_INVALID_ZK_SPEC_VERSION(8),
    MDOC_PROVER_ROOT_DECODING_FAILURE(9),
    MDOC_PROVER_DOCUMENTS_MISSING(10),
    MDOC_PROVER_DOCUMENT_0_MISSING(11),
    MDOC_PROVER_DOCTYPE_MISSING(12),
    MDOC_PROVER_ISSUER_SIGNED_MISSING(13),
    MDOC_PROVER_ISSUER_AUTH_MISSING(14),
    MDOC_PROVER_MSO_MISSING(15),
    MDOC_PROVER_NSIG_MISSING(16),
    MDOC_PROVER_NAMESPACES_MISSING(17),
    MDOC_PROVER_DEVICE_SIGNED_MISSING(18),
    MDOC_PROVER_DEVICE_AUTH_MISSING(19),
    MDOC_PROVER_DEVICE_SIGNATURE_MISSING(20),
    MDOC_PROVER_DEVICE_KEY_MISSING(21),
    MDOC_PROVER_MSO_DECODING_FAILURE(22),
    MDOC_PROVER_VALIDITY_INFO_MISSING(23),
    MDOC_PROVER_DEVICE_KEY_INFO_MISSING(24),
    MDOC_PROVER_ATTRIBUTE_DECODE_FAILURE(25),
    MDOC_PROVER_ATTRIBUTE_EI_MISSING(26),
    MDOC_PROVER_ATTRIBUTE_EV_MISSING(27),
    MDOC_PROVER_ATTRIBUTE_DID_MISSING(28),
    MDOC_PROVER_SIGNATURE_FAILURE(29),
    MDOC_PROVER_DEVICE_SIGNATURE_FAILURE(30),
    MDOC_PROVER_ATTRIBUTE_NOT_FOUND(31),
    MDOC_PROVER_ATTRIBUTE_TOO_LONG(32),
    MDOC_PROVER_TAGGED_MSO_TOO_BIG(33),
    MDOC_PROVER_VERSION_NOT_SUPPORTED(34),
    MDOC_PROVER_ATTRIBUTE_RANDOM_MISSING(35);

    companion object {
        private val map = entries.associateBy(ProverCodeEnum::value)
        fun fromInt(value: Int): ProverCodeEnum? = map[value]
    }
}
