package org.multipaz.mdoc.issuersigned

import org.multipaz.cbor.Bstr
import org.multipaz.cbor.Cbor
import org.multipaz.cbor.CborMap
import org.multipaz.cbor.DataItem
import org.multipaz.cbor.Tagged
import org.multipaz.crypto.Algorithm
import org.multipaz.crypto.Crypto
import kotlinx.io.bytestring.ByteString
import org.multipaz.cbor.buildCborMap

/**
 * A data structure representing `IssuerSignedItem` in ISO/IEC 18013-5:2021.
 *
 * This is stored as a [DataItem] to preserve the order since the result of [calculateDigest] depends on the
 * exact bytes generated by the issuer. Since ISO/IEC 18013-5:2021 Clause 8.1 puts requirements on integers
 * and lengths, the only variable thing is map order meaning it's sufficient to use a [DataItem] instead
 * of the exact bytes from the issuer.
 *
 * Individual components can be retrieved using the [digestId], [random], [dataElementIdentifier], and
 * [dataElementValue] properties.
 *
 * @property dataItem a [DataItem] which is a map with keys `digestID`, `random`, `elementIdentifier`, and `elementValue`
 * as defined in ISO/IEC 18013-5:2021.
 */
data class IssuerSignedItem(
    val dataItem: DataItem
) {
    /**
     * The Digest ID.
     */
    val digestId: Long
        get() = dataItem["digestID"].asNumber

    /**
     * Random value.
     */
    val random: ByteString
        get() = ByteString(dataItem["random"].asBstr)

    /**
     * Data element identifier.
     */
    val dataElementIdentifier: String
        get() = dataItem["elementIdentifier"].asTstr

    /**
     * Data element value.
     */
    val dataElementValue: DataItem
        get() = dataItem["elementValue"]

    /**
     * Calculates the digest of `IssuerSignedItemBytes`.
     *
     * @param algorithm the digest algorithm to use, e.g. [Algorithm.SHA256].
     */
    suspend fun calculateDigest(algorithm: Algorithm): ByteString {
        val encodeIssuerSignedItemBytes =
            Cbor.encode(Tagged(Tagged.ENCODED_CBOR, Bstr(Cbor.encode(dataItem))))
        return ByteString(Crypto.digest(algorithm, encodeIssuerSignedItemBytes))
    }

    companion object {
        /**
         * Constructs a [org.multipaz.mdoc.issuersigned.IssuerSignedItem] from values.
         *
         * @param digestId the digest ID.
         * @param random the random value.
         * @param dataElementIdentifier the data element name.
         * @param dataElementValue the data element value.
         * @return a [org.multipaz.mdoc.issuersigned.IssuerSignedItem].
         */
        fun fromValues(
            digestId: Long,
            random: ByteString,
            dataElementIdentifier: String,
            dataElementValue: DataItem
        ) = IssuerSignedItem(
            dataItem = buildCborMap {
                put("digestID", digestId)
                put("random", random.toByteArray())
                put("elementIdentifier", dataElementIdentifier)
                put("elementValue", dataElementValue)
            }
        )
    }
}
