package org.multipaz.lokalize.engine

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.util.Locale

/**
 * Generates the Kotlin sources that bake the `values` JSON string resources into constants.
 *
 * The generated tree is laid out by package under a source root, so it can be registered as a
 * Kotlin source directory either from `build/` or from a checked-in directory under `src/`.
 *
 * This is deliberately free of Gradle types: [GenerateStringsTask] writes the result into the
 * source tree, while [LokalizeVerifyGeneratedTask] renders the same result into a scratch
 * directory to diff against what is checked in. Both must produce byte-identical output.
 */
class StringsGenerator(
    private val defaultLocale: String,
    private val translationsPackageName: String,
    private val stringKeysPackageName: String,
    private val generatedClassName: String
) {
    /** A generated file, keyed by its path relative to the source root. */
    data class Result(
        val filesByRelativePath: Map<String, String>,
        val languages: List<String>
    )

    /**
     * Reads the `strings.json` in every `values` directory under [resourcesDir] and renders the
     * Kotlin sources.
     *
     * Returns `null` when [resourcesDir] does not exist, so callers can distinguish "nothing to do"
     * from "generated an empty tree".
     */
    fun generate(resourcesDir: File): Result? {
        if (!resourcesDir.exists()) {
            return null
        }

        val valuesDirs = resourcesDir.listFiles { file ->
            file.isDirectory && file.name.startsWith("values")
        }?.sortedBy { it.name } ?: emptyList()

        val files = mutableMapOf<String, String>()
        val languageMaps = sortedMapOf<String, Map<String, String>>()

        valuesDirs.forEach { dir ->
            val stringsFile = File(dir, "strings.json")
            if (!stringsFile.exists()) {
                return@forEach
            }
            val lang = extractLanguageCode(dir.name)
            val jsonObject = Json.parseToJsonElement(stringsFile.readText()).jsonObject
            val map = jsonObject.entries.associate { (key, element) -> key to element.jsonPrimitive.content }

            languageMaps[lang] = map
            files[relativePath(translationsPackageName, "Strings_${lang.replace("-", "_")}.kt")] =
                renderLanguageFile(lang, map)
        }

        files[relativePath(translationsPackageName, "$generatedClassName.kt")] =
            renderAccessObject(languageMaps)

        languageMaps[defaultLocale]?.let { defaultMap ->
            files[relativePath(stringKeysPackageName, "GeneratedStringKeys.kt")] =
                renderStringKeysFile(defaultMap)
        }

        return Result(filesByRelativePath = files.toSortedMap(), languages = languageMaps.keys.toList())
    }

    private fun relativePath(packageName: String, fileName: String): String =
        "${packageName.replace('.', '/')}/$fileName"

    private fun extractLanguageCode(dirName: String): String {
        return when {
            dirName == "values" -> defaultLocale
            dirName.startsWith("values-") -> dirName.substringAfter("values-")
            else -> defaultLocale
        }
    }

    private fun renderLanguageFile(lang: String, map: Map<String, String>): String {
        val safeLang = lang.replace("-", "_")
        return buildString {
            appendLine("package $translationsPackageName")
            appendLine()
            appendLine("/**")
            appendLine(" * Generated strings for language: $lang")
            appendLine(" * DO NOT EDIT - This file is auto-generated by the generateMultipazStrings task")
            appendLine(" */")
            appendLine("internal val strings_$safeLang = mapOf(")

            map.entries.sortedBy { it.key }.forEachIndexed { index, entry ->
                val comma = if (index < map.size - 1) "," else ""
                appendLine("    \"${escapeString(entry.key)}\" to \"${escapeString(entry.value)}\"$comma")
            }

            appendLine(")")
        }
    }

    private fun renderAccessObject(languageMaps: Map<String, Map<String, String>>): String {
        val safeDefault = defaultLocale.replace("-", "_")
        val sortedLangs = languageMaps.keys.sorted()

        return buildString {
            appendLine("package $translationsPackageName")
            appendLine()
            appendLine("/**")
            appendLine(" * Central access point for localized strings.")
            appendLine(" * DO NOT EDIT - This file is auto-generated by the generateMultipazStrings task")
            appendLine(" */")
            appendLine("object $generatedClassName {")
            appendLine()
            appendLine("    private val defaultMap = strings_$safeDefault")
            appendLine()

            sortedLangs.forEach { lang ->
                val safeLang = lang.replace("-", "_")
                appendLine("    private val map_$safeLang = strings_$safeLang")
            }
            appendLine()

            appendLine("    val allLanguages: List<String> = listOf(")
            sortedLangs.forEachIndexed { index, lang ->
                val comma = if (index < sortedLangs.size - 1) "," else ""
                appendLine("        \"$lang\"$comma")
            }
            appendLine("    )")
            appendLine()

            appendLine("    /**")
            appendLine("     * Returns the string map for the given locale.")
            appendLine("     * Falls back to '$defaultLocale' if the locale is not available.")
            appendLine("     *")
            appendLine("     * @param locale The locale code (e.g., \"en\", \"es\", \"de\")")
            appendLine("     * @return Map of string keys to localized values")
            appendLine("     */")
            appendLine("    fun getMapForLocale(locale: String): Map<String, String> {")
            appendLine("        return when (locale) {")
            sortedLangs.forEach { lang ->
                val safeLang = lang.replace("-", "_")
                appendLine("            \"$lang\" -> map_$safeLang")
            }
            appendLine("            else -> defaultMap")
            appendLine("        }")
            appendLine("    }")
            appendLine()

            appendLine("    /**")
            appendLine("     * Returns the localized string for the given key and language.")
            appendLine("     * Falls back to the default language, then to the key itself if not found.")
            appendLine("     *")
            appendLine("     * @param key The string key")
            appendLine("     * @param lang The language code (e.g., \"en\", \"es\", \"de\")")
            appendLine("     * @return The localized string or the key as fallback")
            appendLine("     */")
            appendLine("    fun getString(key: String, lang: String): String {")
            appendLine("        val map = getMapForLocale(lang)")
            appendLine("        return map[key] ?: defaultMap[key] ?: key")
            appendLine("    }")
            appendLine()

            appendLine("    /**")
            appendLine("     * Checks if the given key exists in the specified language.")
            appendLine("     *")
            appendLine("     * @param key The string key to check")
            appendLine("     * @param lang The language code")
            appendLine("     * @return true if the key exists in the language map")
            appendLine("     */")
            appendLine("    fun containsKey(key: String, lang: String): Boolean {")
            appendLine("        return getMapForLocale(lang).containsKey(key)")
            appendLine("    }")

            appendLine("}")
        }
    }

    private fun renderStringKeysFile(defaultMap: Map<String, String>): String {
        val entries = defaultMap.keys.sorted().map { key ->
            val constName = key
                .uppercase(Locale.US)
                .replace(Regex("[^A-Z0-9]+"), "_")
                .trim('_')
            constName to key
        }

        return buildString {
            appendLine("package $stringKeysPackageName")
            appendLine()
            appendLine("/**")
            appendLine(" * Generated string resource keys from values/strings.json.")
            appendLine(" * DO NOT EDIT - This file is auto-generated by the generateMultipazStrings task")
            appendLine(" */")
            appendLine("object GeneratedStringKeys {")
            appendLine()
            entries.forEach { (constName, key) ->
                appendLine("    const val $constName = \"${escapeString(key)}\"")
            }
            appendLine("}")
        }
    }

    private fun escapeString(str: String): String {
        return str
            .replace("\\", "\\\\")  // Backslash
            .replace("\"", "\\\"")   // Double quotes
            .replace("$", "\$")       // Dollar sign for string interpolation
            .replace("\n", "\\n")      // Newline
            .replace("\r", "\\r")      // Carriage return
            .replace("\t", "\\t")      // Tab
    }
}
