package org.multipaz.request

import org.multipaz.trustmanagement.TrustMetadata
import org.multipaz.presentment.PresentmentSource

/**
 * Represents a requester identity that is trusted by a presenter, with additional metadata.
 *
 * This object is typically generated by [PresentmentSource.resolveTrust].
 *
 * @param identity identity of the Verifier that requested presentment from the list in
 *  [Requester.requesterIdentities]
 * @param trustMetadata metadata related to the [Requester] in the context of the presentment
 *  request that provides branding and other information about the requester
 */
open class TrustedRequesterIdentity(
    open val identity: RequesterIdentity,
    open val trustMetadata: TrustMetadata
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is TrustedRequesterIdentity) return false
        return identity == other.identity && trustMetadata == other.trustMetadata
    }

    override fun hashCode(): Int {
        var result = identity.hashCode()
        result = 31 * result + trustMetadata.hashCode()
        return result
    }

    override fun toString(): String {
        return "TrustedRequesterIdentity(identity=$identity, trustMetadata=$trustMetadata)"
    }
}