package org.multipaz.request

import org.multipaz.trustmanagement.TrustMetadata
import org.multipaz.presentment.PresentmentSource

/**
 * Represents a requester identity that is trusted by a presenter, with additional metadata.
 *
 * This object is typically generated by [PresentmentSource.resolveTrust].
 *
 * TODO: should this be an open class, so that app developers could pass custom trust information?
 *
 * @param identity identity of the Verifier that requested presentment from the list in
 *  [Requester.requesterIdentities]
 * @param trustMetadata metadata related to the [Requester] in the context of the presentment
 *  request that provides branding and other information about the requester
 */
class TrustedRequesterIdentity(
    val identity: RequesterIdentity,
    val trustMetadata: TrustMetadata
)