build:
  maxIssues: 0

output-reports:
  active: true
  exclude:
   - 'TxtOutputReport'
   - 'XmlOutputReport'
   - 'MdOutputReport'
   - 'SarifOutputReport'
#   - 'HtmlOutputReport'

comments:
  active: true
  UndocumentedPublicClass:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**', '**/build/generated/**']
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
    searchInProtectedClass: false
    ignoreDefaultCompanionObject: true
  UndocumentedPublicFunction:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**', '**/build/generated/**']
    searchProtectedFunction: false
  UndocumentedPublicProperty:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**', '**/build/generated/**']
    searchProtectedProperty: false